<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://driveitwith.me</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/auto</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/auto-reviews</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/auto-repairs</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/car-care</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/car-device</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/auto-tips-for-begining</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/moto</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/moto-reviews</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/moto-repairs</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/moto-care</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/law</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/category/helpful</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/best-rated</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/best-views</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/best-comments</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/about</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/rules</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/login</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/register</loc>
    </url>
    <url>
        <loc>https://driveitwith.me/posts</loc>
    </url>
    @foreach($data as $key => $item)
    <url>
        <loc>{{ $item['link'] }}</loc>
    </url>
    @endforeach
</urlset>