<article class="comment-card" data-comment-id="{{ $comment->id }}">
        <header class="comment-header">
                <div class="comment-user">
                            <a href="{{ route('user.profile', $comment->user->username) }}" class="user-avatar">
                                            <img src="{{ $comment->user->profile->avatar }}" 
                                                                 alt="{{ $comment->user->username }}" 
                                                                                      loading="lazy"
                                                                                                           width="40"
                                                                                                                                height="40">
                                                                                                                                            </a>
                                                                                                                                                        <a href="{{ route('user.profile', $comment->user->username) }}" 
                                                                                                                                                                       class="user-name">
                                                                                                                                                                                      {{ $comment->user->username }}
                                                                                                                                                                                                  </a>
                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                  <div class="comment-actions">
                                                                                                                                                                                                                              <button class="comment-toggle-publish" 
                                                                                                                                                                                                                                                  type="button"
                                                                                                                                                                                                                                                                      aria-label="{{ $comment->is_verified ? __('Unpublish comment') : __('Publish comment') }}"
                                                                                                                                                                                                                                                                                          data-comment-id="{{ $comment->id }}">
                                                                                                                                                                                                                                                                                                          @if($comment->is_verified)
                                                                                                                                                                                                                                                                                                                              <x-icons.checkmark class="icon published" />
                                                                                                                                                                                                                                                                                                                                              @else
                                                                                                                                                                                                                                                                                                                                                                  <x-icons.square class="icon unpublished" />
                                                                                                                                                                                                                                                                                                                                                                                  @endif
                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                          <time datetime="{{ $comment->created_at->toIso8601String() }}" 
                                                                                                                                                                                                                                                                                                                                                                                                                            class="comment-date">
                                                                                                                                                                                                                                                                                                                                                                                                                                              {{ $comment->created_at->diffForHumans() }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </time>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div class="comment-body">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>{{ $comment->message }}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <footer class="comment-footer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {{ __('Comment on the article') }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <a href="{{ route('posts.show', $comment->post->slug) }}">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {{ $comment->post->name }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </article>